new branch
Kseniyashsurinova/java-filmorate pull request #4
Opened 2023-03-08 13:14 UTC by Kseniyashsurinova

2023-03-08 14:01 UTC, Kseniyashsurinova commented
new

2023-03-08 15:19 UTC, NikolaiDem requested changes
Ксения, нужно починить сборку.

2023-03-08 15:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void checkFilmValidation(Film film) {
Вместо ручной валидации можно использовать аннотации из javax.validation.constraints.*. Их указать для полей в Film и User. А чтобы они сработали, для аргументов метода контроллера указать @Valid.

2023-03-08 15:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void checkUserValidation(User user) {
Вместо ручной валидации можно использовать аннотации из javax.validation.constraints.*. Их указать для полей в Film и User. А чтобы они сработали, для аргументов метода контроллера указать @Valid.

2023-03-08 15:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getName().isEmpty() || film.getName().isBlank()) {
Еще учесть проверки на null (или использовать аннотацию NotNull)

2023-03-08 15:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getLogin().isEmpty() || user.getLogin().isBlank()) {
Еще учесть проверки на null (или использовать аннотацию NotNull)

2023-03-08 15:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +import junit.runner.Version;
Лишний импорт.

2023-03-08 15:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +
Кодстайл : лишняя строка.

2023-03-08 15:19 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +
Кодстайл : лишняя строка.

2023-03-10 20:37 UTC, NikolaiDem requested changes

2023-03-10 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull(message = "Почта не может быть пусто")
NotNull можно удалить для строки, если уде указано NotBlank.
И для остальных String полей аналогично.

2023-03-10 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank(message = "Название не может быть пустым")
NotNull можно удалить для строки, если уде указано NotBlank.
И для остальных String полей аналогично.

2023-03-10 20:37 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank(message = "Дата релиза не может быть пустым")
NotBlank используется только для CharSequence.

2023-03-12 09:38 UTC, Kseniyashsurinova commented
try3

2023-03-12 09:40 UTC, merged